import React, { useState } from 'react';
import { ArrowUpRight, BookOpen, Code2, Github, Mail, Menu, MessageCircle, Send, User, X } from 'lucide-react';
import './styles.css';

const api = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
const projects = [
  ['Project One', 'Web experience', 'A clean, responsive project space for turning an idea into a useful product.', 'coral'],
  ['Project Two', 'JavaScript build', 'Interactive frontend work with thoughtful states and a smooth user journey.', 'lime'],
  ['Project Three', 'Learning tool', 'A focused tool that makes complex concepts easier to explore and remember.', 'blue'],
  ['Project Four', 'Full-stack app', 'A practical product connecting a friendly interface to a dependable backend.', 'yellow'],
  ['Project Five', 'Experiment', 'Small experiments that sharpen craft, curiosity, and engineering judgment.', 'pink'],
  ['Project Six', 'Coming soon', 'This space is ready for the next idea you want to bring to life.', 'green']
];

function App() {
  const [menuOpen, setMenuOpen] = useState(false), [auth, setAuth] = useState(null), [noteTab, setNoteTab] = useState('HTML'), [user, setUser] = useState(null), [notice, setNotice] = useState(''), [adminKey, setAdminKey] = useState(''), [adminRows, setAdminRows] = useState([]);
  const [form, setForm] = useState({ firstName: '', email: '', description: '' });
  const update = e => setForm({ ...form, [e.target.name]: e.target.value });
  const submit = async (e, endpoint, withFile = false) => { e.preventDefault(); setNotice('Sending...'); const body = withFile ? new FormData(e.currentTarget) : JSON.stringify({ ...form, type: endpoint }); try { const res = await fetch(`${api}/${endpoint}`, { method: 'POST', headers: withFile ? {} : { 'Content-Type': 'application/json' }, body }); if (!res.ok) throw new Error(); setNotice('Received. Thank you!'); e.currentTarget.reset(); } catch { setNotice('Backend is not connected yet. Add the API URL after deployment.'); } };
  const loadAdmin = async table => { setNotice('Loading submissions...'); try { const res = await fetch(`${api}/admin/${table}`, { headers: { 'x-admin-key': adminKey } }); if (!res.ok) throw new Error(); setAdminRows(await res.json()); setNotice(''); } catch { setNotice('Admin access failed. Check the key and backend URL.'); } };
  return <>
    <header className="nav"><a className="brand" href="#home">LK<span>.</span></a><button className="menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Menu">{menuOpen ? <X /> : <Menu />}</button><nav className={menuOpen ? 'open' : ''}>{['home','about','projects','notes','contact'].map(item => <a key={item} href={`#${item}`} onClick={() => setMenuOpen(false)}>{item}</a>)}<button className="login-btn" onClick={() => setAuth('login')}><User size={16} /> Login</button></nav></header>
    <main>
      <section id="home" className="hero"><div className="hero-copy"><p className="kicker">DEVELOPER • BUILDER • LEARNER</p><h1>Ideas become<br /><em>useful things.</em></h1><p className="lead">Hi, I’m Lavish Kumar. I build clear, curious digital experiences and share what I learn along the way.</p><div className="actions"><a className="button primary" href="#projects">See my work <ArrowUpRight size={17} /></a><a className="text-link" href="#contact">Let’s talk <ArrowUpRight size={16} /></a></div></div><div className="hero-art"><div className="stamp">MAKE<br />IT<br /><strong>REAL</strong></div><div className="code-card"><span>&lt;hello world /&gt;</span><br /><b>const</b> curiosity = true;<br /><b>build</b>(somethingUseful);</div></div></section>
      <section id="about" className="about section"><div className="section-label">01 / ABOUT</div><div><h2>A developer with a<br /><span>builder’s mindset.</span></h2><p>I enjoy making websites that feel human: easy to understand, pleasant to use, and built with enough care under the hood to last. This space is where I keep my work, notes, and an open door for good questions.</p><div className="facts"><div><strong>01</strong><small>Curious by default</small></div><div><strong>02</strong><small>Learning in public</small></div><div><strong>03</strong><small>Building with care</small></div></div></div></section>
      <section id="projects" className="section projects"><div className="section-head"><div className="section-label">02 / SELECTED WORK</div><h2>Things I’ve <span>made.</span></h2></div><div className="project-grid">{projects.map(([title, type, text, color], i) => <article className={`project ${color}`} key={title}><div className="project-no">0{i + 1}</div><Code2 size={28} /><p>{type}</p><h3>{title}</h3><span>{text}</span><a href="#contact" aria-label={`Open ${title}`}><ArrowUpRight size={20} /></a></article>)}</div></section>
      <section id="notes" className="notes section"><div className="section-label">03 / STUDY ROOM</div><div className="notes-intro"><h2>Notes for the<br /><span>next version.</span></h2><p>Short, practical notes uploaded from the admin panel. New chapters will appear in their matching subject automatically.</p></div><div className="note-tabs">{['HTML','CSS','JavaScript'].map(tab => <button className={noteTab === tab ? 'active' : ''} onClick={() => setNoteTab(tab)} key={tab}><BookOpen size={17} /> {tab} NOTES</button>)}</div><div className="note-list"><div><span className="pdf">PDF</span><strong>{noteTab} Chapter 1</strong><small>Foundations • Available soon</small><ArrowUpRight size={18} /></div><div><span className="pdf">PDF</span><strong>{noteTab} Chapter 2</strong><small>Practice notes • Available soon</small><ArrowUpRight size={18} /></div></div></section>
      <section className="forms section"><div className="form-box"><div className="section-label">04 / ASK A QUESTION</div><h2>Stuck on something?<br /><span>Send it over.</span></h2><p>Login to attach a PDF or screenshot with your doubt.</p>{user ? <form onSubmit={e => submit(e, 'doubts', true)}><div className="two"><input required name="firstName" placeholder="First name" /><input required name="lastName" placeholder="Last name" /></div><input required type="email" name="email" placeholder="Email address" /><input type="file" name="attachment" accept=".pdf,.png,.jpg,.jpeg" /><textarea required name="description" placeholder="Describe your doubt"></textarea><button className="button primary">Send doubt <Send size={16} /></button></form> : <button className="button primary" onClick={() => setAuth('login')}>Login to ask <User size={16} /></button>}</div><div id="contact" className="form-box dark"><div className="section-label">05 / CONTACT</div><h2>Have a thought?<br /><span>Say hello.</span></h2><form onSubmit={e => submit(e, 'messages')}><input required name="firstName" value={form.firstName} onChange={update} placeholder="Your name" /><input required type="email" name="email" value={form.email} onChange={update} placeholder="Email address" /><textarea required name="description" value={form.description} onChange={update} placeholder="Your message"></textarea><button className="button light">Send message <Mail size={16} /></button></form></div></section>
      <section className="feedback section"><div><div className="section-label">06 / FEEDBACK</div><h2>Help me make this<br /><span>space better.</span></h2></div><form onSubmit={e => submit(e, 'feedback')}><input required name="firstName" placeholder="Your name" /><textarea required name="description" placeholder="What did you think?"></textarea><button className="button outline">Share feedback <MessageCircle size={16} /></button></form></section><section id="admin" className="admin section"><div className="section-label">PRIVATE / ADMIN</div><h2>Inbox <span>control.</span></h2><div className="admin-bar"><input type="password" value={adminKey} onChange={e => setAdminKey(e.target.value)} placeholder="Admin key" /><button className="button primary" onClick={() => loadAdmin('messages')}>Messages</button><button className="button outline" onClick={() => loadAdmin('feedback')}>Feedback</button><button className="button outline" onClick={() => loadAdmin('doubts')}>Doubts</button></div><div className="admin-list">{adminRows.length ? adminRows.map(row => <article key={row.id}><strong>{row.name}</strong><small>{row.email || 'Feedback'} • {new Date(row.created_at).toLocaleString()}</small><p>{row.message || row.description}</p>{row.attachment_url && <a href={row.attachment_url} target="_blank">Open attachment <ArrowUpRight size={15} /></a>}</article>) : <p className="muted">Choose a submission type to view your inbox.</p>}</div></section>
    </main><footer><span>© 2026 Lavish Kumar</span><a href="#home">Back to top ↑</a><a href="https://github.com" target="_blank"><Github size={17} /> GitHub</a></footer>{notice && <div className="toast">{notice}<button onClick={() => setNotice('')}><X size={15} /></button></div>}{auth && <Auth mode={auth} close={() => setAuth(null)} loggedIn={name => { setUser(name); setAuth(null); setNotice(`Welcome, ${name}`); }} />}</>;
}
function Auth({ mode, close, loggedIn }) { const [name, setName] = useState(''); return <div className="modal-backdrop"><div className="modal"><button className="close" onClick={close}><X /></button><div className="section-label">{mode === 'login' ? 'WELCOME BACK' : 'JOIN THE ROOM'}</div><h2>{mode === 'login' ? 'Log in to continue.' : 'Create your account.'}</h2><form onSubmit={e => { e.preventDefault(); loggedIn(name || 'Friend'); }}><input required value={name} onChange={e => setName(e.target.value)} placeholder="Full name" /><input required type="email" placeholder="Email address" /><input required type="password" placeholder="Password" /><button className="button primary">{mode === 'login' ? 'Login' : 'Sign up'} <ArrowUpRight size={16} /></button></form><p className="switch">Demo mode: authentication connects after Supabase setup.</p></div></div>; }
createRoot(document.getElementById('root')).render(<App />);